### ISSUE TITLE
Error installing phantom via npm install phantom

### ISSUE THREAD

**Issue by MMRandy** [sgentle/phantomjs-node#107]
Hardware: Mac with Windows VM (Windows 7)
Running Node v0.10.19 and NPM 1.3.11.  

I can run phantom at prompt, so I'm good there.  After running npm install phantom, it seems to install all the required modules fine, but blows up on the build process with the following (any help greatly appeciated!):

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'weakref.vcxproj' is invalid.  Platform='x64'. You
 may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [C:\bitbuck
et\seo-handler\node_modules\phantom\node_modules\dnode\node_modules\weak\build\weakref.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\bitbucket\seo-handler\node_modules\phantom\node_modules\dnode\node_modules\weak
gyp ERR! node -v v0.10.19
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok

**Comment by amir20** [comment]
Looks #93 fixes this.

**Comment by whitelynx** [comment]
Actually, the OP's error is _not_ the same as the ones mentioned later; it's specifically building this _inside a Windows 7 VM_. It seems like this issue may come from having a 64-bit Node.js install, but only a 32-bit MS Visual C++ install.
