### ISSUE TITLE
TypeError: Cannot read property 'binary' of null

### ISSUE THREAD

**Issue by freshlogic** [sgentle/phantomjs-node#108]
phantom.create(function(ph) {}, null, 12300);

Gives me the following error on v0.5.2:

node_modules/phantom/phantom.js:82
      if ((_ref = options.binary) == null) {
                         ^
TypeError: Cannot read property 'binary' of null

Works fine on v0.5.1

**Comment by amir20** [comment]
Cleaning out old bugs.
