### ISSUE TITLE
Error installing phantomjs-node via npm install phantom

### ISSUE THREAD

**Issue by kamalt** [sgentle/phantomjs-node#109]
My system environment details:

Operating System: Windows 7 (64bit)
Node.js: v0.10.20
Python: v2.7
Phantomjs: v1.9.2

In command prompt, tried installing "phantomjs-node" using the command "npm install phantom".

Installation failed with build error. Below is the complete error info,

> weak@0.2.2 install C:\Windows\system32\node_modules\phantom\node_modules\dnode
\node_modules\weak
> node-gyp rebuild
C:\Windows\system32\node_modules\phantom\node_modules\dnode\node_modules\weak>no
de "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_module
s\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v0.10.20/node-v0.10.20.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.20/node-v0.10.20.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.20/x64/node.lib
gyp http GET http://nodejs.org/dist/v0.10.20/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.20/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.20/node.lib

MSBUILD : error MSB1009: Project file does not exist.
Switch: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\phantom\node_modules\dnode\node_mo
dules\weak
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by amir20** [comment]
Cleaning out old bugs. If it is still valid, let's reopen.
