### ISSUE TITLE
return value from page.evaluate 

### ISSUE THREAD

**Issue by josx** [sgentle/phantomjs-node#110]
I cant return a value to page scope, is that possible with phantomjs-node ( i dont want, need to use another callback)

I am trying to do the following:

```
var page = require('webpage').create();
page.open('http://localhost, function(status) {
    var title = page.evaluate(function() {
        return document.title;
    });

... DO WHATEVER I WANT WITH TITLE ...

    phantom.exit();
});
```

**Comment by omouse** [comment]
I have a feeling the documentation needs to be updated: http://phantomjs.org/api/webpage/method/evaluate.html

**Comment by amir20** [comment]
This issue is outdated since version 1. I am not sure what you mean by updating documentation. It already reflects the latest code.

**Comment by omouse** [comment]
you're right it does, after some work I was able to get it working correctly. it would be nice to have more examples though in any case.

**Comment by amir20** [comment]
There is documentation at https://github.com/amir20/phantomjs-node#pageevaluate But pull requests are welcomed. There is an example folder which you are more than welcome to improve on.
