### ISSUE TITLE
phantom.create callback doesn't work

### ISSUE THREAD

**Issue by shaniu00** [sgentle/phantomjs-node#111]
I have two server host
centos5.9 node10.20 phantomjs 1.92 python Python 2.7.3
var phantom = require("phantom");
phantom.create( function (ph) {
             
                console.log("cb...........");
           
 });
one can work ,the other cann't work. and throw nothing.

**Comment by amir20** [comment]
Cleaning out old bugs. If it is still valid, let's reopen.
