### ISSUE TITLE
phantomjs processes not closed on SIGTERM

### ISSUE THREAD

**Issue by ysimonson** [sgentle/phantomjs-node#121]
If you send a SIGTERM to the process, the `exit` event on `process` will never fire. Ditto for SIGINT: https://groups.google.com/forum/#!topic/nodejs/h94vnnXpKes

Consequently, the code to cleanup phantomjs sub-processes will never run: https://github.com/sgentle/phantomjs-node/blob/master/phantom.coffee#L30

It is possible to listen specifically for SIGTERM/SIGINT though: http://nodejs.org/api/process.html#process_signal_events

**Comment by anroots** [comment]
```
root@d1dcfc411ef7:~# node_modules/.bin/phantomjs --webdriver=4444 &
[1] 14992
root@d1dcfc411ef7:~# PhantomJS is launching GhostDriver...
[INFO  - 2015-08-18T07:18:17.221Z] GhostDriver - Main - running on port 4444
ps -A | grep phan
14994 ?        00:00:00 phantomjs

[1]+  Stopped                 node_modules/.bin/phantomjs --webdriver=4444
root@d1dcfc411ef7:~# kill $!
root@d1dcfc411ef7:~# ps -A | grep phan
14994 ?        00:00:00 phantomjs
```

Still present. Unable to kill the process gracefully, `SIGKILL` works.
