### ISSUE TITLE
Open pages in a loop

### ISSUE THREAD

**Issue by oreporan** [sgentle/phantomjs-node#156]
As written in the wiki:

>ph.createPage() makes new PhantomJS WebPage objects, so use that if you want to open lots of webpages. 

I am interested in opening *and* evaluating each page I open. However I think the process only evaluates one of the pages in my loop.

If I want to open and evaluate many websites, should I create several processes? i.e

>You can also make multiple phantomjs processes by calling phantom.create('flags', { port: someDiffNumber})

When doing this, I get some kind of multi-processing problem which creates duplicates of my evaluate callback..
Also - what is the 'flags' param?

I have written a question on stackoverflow - 
http://stackoverflow.com/questions/23218531/phantomjs-node-in-a-for-loop

**Comment by amir20** [comment]
Since your question was answered on SO. Closing.
