### ISSUE TITLE
page.render() callback fails on AMI

### ISSUE THREAD

**Issue by aesopwolf** [sgentle/phantomjs-node#181]
On my Mac (phantomjs was installed using homebrew), the callback fires successfully. However, on my Amazon AMI production machine (phantomjs installed with the prebuilt binary), the callback never fires!

```
page.render('example.pdf', function() {
  console.log("file was saved");
});
```

I'm not even sure how I would debug this. Any tips, guiding advice?

**Comment by amir20** [comment]
Did you find the problem?
