### ISSUE TITLE
Seemingly CORS issue

### ISSUE THREAD

**Issue by mathurs** [sgentle/phantomjs-node#186]
When I run this simple snippet

var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
    page.open("http://www.google.com", function (status) {
      console.log("opened google? ", status);
      page.evaluate(function () { return document.title; }, function (result) {
        console.log('Page title is ' + result);
        ph.exit();
      });
    });
  });
});

I am getting the following error:
phantom stdout: XMLHttpRequest cannot load http://localhost:49188/dnode/info. Cannot make any requests from null.

However, when I directly run this via phantomjs

var page = require('webpage').create();
page.open('http://www.google.com', function() {
  page.render('www.google.png');
  phantom.exit();
});

It successfully renders the page. Any ideas why that might be ?

Thanks

**Comment by KyleLH** [comment]
Bump? Has anyone looked at this?

**Comment by arrowing** [comment]
You can set the options like this:

var options = {
  port: 16000,
  hostname: "192.168.1.3",
  path: "/phantom_path/"
}

phantom.create(function, options);

**Comment by KyleLH** [comment]
@arrowing ahh sounds good, thanks!
