### ISSUE TITLE
module hijacks process SIGINT signal event

### ISSUE THREAD

**Issue by devcollectief** [sgentle/phantomjs-node#192]
Handling `process.on('SIGINT')` is important for graceful shutdown of cluster workers that use this module. A trick would be to remove listeners of `process` events after the `require()` of the module. That results in an issue however

```
AssertionError: abnormal phantomjs exit code: 130
    at Console.assert (console.js:102:23)
    at ChildProcess.<anonymous> (node_modules/phantom/phantom.js:132:28)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
````

Is there a quick fix or does a pull request need be submitted to fix this? I am not sure if there is something that can be done in the application level above the module perhaps...

**Comment by amir20** [comment]
I don't understand if this was already merged. I am closing to clean up bugs.
