### ISSUE TITLE
Problem with "weak dependecy" 

### ISSUE THREAD

**Issue by PainKKKiller** [sgentle/phantomjs-node#197]
This solution doesn't work for me: 
var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
    /* the page actions */
  });
}, {
  dnodeOpts: {
    weak: false
  }
});
Node still gives error "can't find module weak".  I can't install weak module, I have MS Visual Studio 2013, and Windows SDK installed, but still there is no way for me to install it. So I can't use phantomJS on my system (Windows 7 64bit)

**Comment by jitui2i** [comment]
Hope this is not the right solution for using one module why we have to install a package of software ... is there any other way i tried with node v 0.12 also it doesnot work for me

**Comment by sarasfox** [comment]
I have the weak issue on iojs

**Comment by chill117** [comment]
I had this same issue and solved it like this:

```js
var options = {
  dnodeOpts: { weak: false }
};

var phantom = require('phantom');

phantom.create(function(ph) {

    return ph.createPage(function(page) {

      return page.open("http://www.google.com", function(status) {

         console.log("opened google? ", status);

         return page.evaluate((function() {

            return document.title;

      }), function(result) {

        console.log('Page title is ' + result);
        return ph.exit();

      });

    });

  });

}, options);
```

Note the `options` being passed to the `phantom.create()` method. I got the above solution from this [ stackoverflow answer](https://stackoverflow.com/a/28392391/1157309).
