### ISSUE TITLE
https address opens blank page

### ISSUE THREAD

**Issue by avitavdi** [sgentle/phantomjs-node#204]
using this great rep, really good staff!
Trying to open https page, it always gives blank page, i guess it got something to do with SSL premissions or protocol setup on phantom.
How do i set up the SSL protocol on phantom object?
Is there specific way to successfully open https page?

Thanks in advance

**Comment by amir20** [comment]
This was related to ssl issues. I remember debugging this. In the latest nodejs, it is fixed to use the correct protocol.
