### ISSUE TITLE
Including external JS does not render a PDF

### ISSUE THREAD

**Issue by toddmoto** [sgentle/phantomjs-node#207]
When including an external JS library in the HTML file, the PDF doesn't render.

Response is a string from a compiled handlebars template.

When removing the link to the external JS file, the PDF renders fine.

```js
phantom.create(function (ph, error) {
    ph.createPage(function (page, error) {
      page.setContent(response);

      page.set('paperSize', {
        format: 'A4'
      }, function() {
        page.render(fileName, function (error) {
        });
        ph.exit();
      });
    });
});
```

**Comment by amir20** [comment]
Closing old tickets. Let me know if you ever found a solution.
