### ISSUE TITLE
Is there anyway to support CasperJS ?

### ISSUE THREAD

**Issue by falkenlabs** [sgentle/phantomjs-node#213]
Hi,  
I tried to make this module compatible with CasperJS (based on PhantomJS).
I tried to change the binary name in phantom.js file but without any success.. 

```
options.binary = options.path + 'casperjs';
```

**Comment by amir20** [comment]
I don't think we plan to ever support casper. That's a different library and should _probably_ be a different node module.

**Comment by HugoPoi** [comment]
Just a little update about using CasperJS with phantom.
I write a scraper for Google https://github.com/majewan/node-google-scraper.
Not the best solution but it works well.
