### ISSUE TITLE
How to fix 'Error: spawn Unknown system errno 203' on Windows machine ?

### ISSUE THREAD

**Issue by vdzundza** [sgentle/phantomjs-node#218]
I've installed phantomjs and this phantom packages.
I used 1.9.8 phantomjs version. When I tried to run example I have got this error
 "error: uncaughtException: spawn Unknown system errno 203"
Detailed trace is here: http://pastebin.com/Xw9nmk8w

**Comment by amir20** [comment]
Cleaning up old tickets. Reopen if still valid.
