### ISSUE TITLE
crash onAlert

### ISSUE THREAD

**Issue by lijiaqigreat** [sgentle/phantomjs-node#230]
running this directly on phantomjs has no problem
```javascript
var page=require('webpage').create();
page.onAlert = function(msg) {
  console.log('ALERT: ' + msg);
};
page.open('www.google.com',function(){
  page.evaluate(function(){
    alert('!!!');
  });
});
```
while the following will crash phantomjs when running on node with phantomjs-node
```javascript
var phantom=require("phantom");
phantom.create(function(ph){
  console.log("ph");
  ph.createPage(function(page){
    page.set('onAlert' , function(msg) {
      //console.log('ALERT: ' + msg);
    });
    page.open('www.google.com',function(){
      page.evaluate(function(){
        alert('!!!');
      });
    });
  });
});
```
I tried `onLoadFinished`, and there is no problem.
os: linux 64
phantomjs version: 1.9.7
phantom version: 0.7.1

**Comment by bradleyayers** [comment]
You probably want

    page.onAlert(function(msg) {
      console.log('ALERT: ' + msg);
    });

But unfortunately this isn't supported. Could probably be done with simple patch.
