### ISSUE TITLE
ph.addCookie's signature doesn't match the API docs

### ISSUE THREAD

**Issue by pscollins** [sgentle/phantomjs-node#233]
The supplied addCookie method:

     addCookie: (name, value, domain, cb=->)

doesn't match the signature in the PhantomJS API documentation:

    addCookie(Cookie) {boolean}

Clearly, using a callback rather than returning a `boolean` is unavoidable, but it seems like there's no reason to deviate from the PhantomJS API when it's not necessary --- especially since the provided function gives you less control over the cookie that you add.

**Comment by pscollins** [comment]
Hey -- this is my first commit to an open-source project, so I apologize if I've done anything wrong. I added in unit tests for the new change, and everything seems to be passing.

**Comment by amir20** [comment]
Next time put `Fixes #233` in the commit message and github will automatically close this issue.
