### ISSUE TITLE
Provide control for the stdout

### ISSUE THREAD

**Issue by gdanov** [sgentle/phantomjs-node#235]
Searched, but found nothing related to the stfout.
Some way to have access to what phantomjs writes to stdout would be very nice so that I can control (filter) or redirect it to my "main" logic.
Mechanism similar to onResourceRequested(f1, f2) would be very comfortable

**Comment by pscollins** [comment]
Unless I'm misunderstanding, this can be done with the `phantom.create` method, via the `options.onStdout` parameter. Relevant snippet, from `phantom.coffee`:

    module.exports =
        create: ->
            args = []
            options = {}
            for arg in arguments
                switch typeof arg
                ...
                when 'object' then options = arg
    ...
    ps.stdout.on 'data', options.onStdout || (data) -> console.log "phantom stdout: #{data}"

So calling 

    phantom.create onStdout: (data) -> if /ERROR/.test data then console.log "error! #{data}"

could do something like what you want.

**Comment by amir20** [comment]
Good find @pscollins :+1:
