### ISSUE TITLE
Unable to start with remote debugger

### ISSUE THREAD

**Issue by misterdai** [sgentle/phantomjs-node#238]
I'm trying to use the Web Inspector from PhantomJS to help with debugging my code, but whenever I enable it (through use of the parameters), the code will error with the following complaint.

```
Error
line: 5429
message: "'undefined' is not a function (evaluating 'core_require('webpage')')"
sourceId: 3905936
sourceURL: "about:blank"
stack: "TypeError: 'undefined' is not a function (evaluating 'core_require('webpage')')...
```

And here is an example of the code used to create the phantom process.

```javascript
phantom.create('--remote-debugger-port=9000', '--remote-debugger-autorun=yes', function(process) {
  console.log('Never gets this far when remote debugger is enabled... :('); 
});
```

The remote debugger is available (on http://localhost:9000) however as the error doesn't end the phantom & node processes.  Running `__run();` in the debugger manually will cause the same error.

If I leave off the `--remote-debugger-autorun=yes` option, the code will not progress and the same error will be presented if I execute `__run();` in the debugger.

**Comment by misterdai** [comment]
Don't know if it helps, but I ran the following:

`phantomjs --remote-debugger-port=9000 --remote-debugger-autorun=yes node_modules/phantom/shim.js 8888 127.0.0.1`

Same error.  So right up the top of the `shim.js` file I put a `console.log(require);`.  It outputs `undefined` if the debugger is enabled, but is present without the debugger.

So... with blatant disregard to my own welfare I added this to the top of the `shim.js` file:

```javascript
if (typeof require === 'undefined') require = self.require;
```

Which worked, no more error and I can now use remote debugging :).  I've no idea why `require` is missing when I flag the debugger on though, so no one should accept this as a fix without further investigation as to why or any potential knock-on affects of adding this line.

**Comment by fabriciomassula** [comment]
I'm with the same issue here... can't start the phantom on debug mode!

**Comment by bitlyfied** [comment]
same issue here. thanks @misterdai for the trick!

but after patching shim.js I had another fatal error:
```
phantom stdout: XMLHttpRequest cannot load http://127.0.0.1:59267/dnode/info. Cannot make any requests from null.
```
I also fixed that by running Phantom with **web-security** flag set to false.
