### ISSUE TITLE
`page.clearMemoryCache()` not working

### ISSUE THREAD

**Issue by fancyoung** [sgentle/phantomjs-node#245]
`page.clearMemoryCache()` is not in phantomjs api page, but it's useful to clean cache in 2.0.
But it seemed not working in phantomjs-node

**Comment by RavenHursT** [comment]
+1... this is a VERY desirable feature.

**Comment by hideov** [comment]
+1

**Comment by gondo** [comment]
+1

**Comment by amir20** [comment]
Looks like the fix was added by @mjgp2. He should create a pull request to add it this repo.
