### ISSUE TITLE
phantomjs-node: You don't have 'phantomjs' installed on Windows

### ISSUE THREAD

**Issue by jitui2i** [sgentle/phantomjs-node#247]
Hi,
I am using phantomjs to generate pdf but i m stuck when am using in windows machine it says you dont have phantomjs installed on windows.
But when i type phantomjs it give me the prompt of phantomjs.

var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
    /* the page actions */
  });
}, {
  dnodeOpts: {
    weak: false
  }
});

Please Can anyone help regard this ...

**Comment by interisti** [comment]
Same here, Windows 8.1

**Comment by mariantatarau** [comment]
your path from options to phantom.exe, is correct ? like C:\\user\phantomjs ?

**Comment by chill117** [comment]
The error message `You don't have 'phantomjs' installed` is an internal error from phantomjs-node. I ran into this error myself, and I managed to fix it like this:

```js
var phantom = require('phantom');

var options = {
		path: '/usr/local/bin/'
};

phantom.create(function (ph) {
	ph.createPage(function (page) {
		page.open("http://www.google.com", function (status) {
			console.log("opened google? ", status);
			page.evaluate(function () { return document.title; }, function (result) {
				console.log('Page title is ' + result);
				ph.exit();
			});
		});
	});
}), options);
```

Notice the `options` being passed to the `phantom.create()` method. The `path` option should be the full path to the directory that contains your phantomjs binary.

**Comment by lebedkin** [comment]
@chill117 I copy the exact code and still have an error:
```
<path>file.js:17
}), options);
           ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by chill117** [comment]
@lebedkin There was a syntax error in the code I posted. Sorry about that. I've corrected the error.
