### ISSUE TITLE
Memory leak in phanta array

### ISSUE THREAD

**Issue by Oted** [sgentle/phantomjs-node#251]
Hi! 

So i've been having these memory leak for a long time and i finally managed to locate where it was by digging into the phantom.js file. When i am using phantom i have multiple instances of them running in parallel but it seems like when i call page.close()/phantomJS.exit() the instance of the phantom in the phanta array does not get cleared out. This makes the array grow bigger end bigger until my the main process exits. Im not sure how it is suppose to work or if i am doing something wrong but i managed to find out what was causing the issue.

````
...return ps.on('exit', function(code, signal) {
          var p;
          httpServer.close();
          if (phantom) {
            phanta = (function createPhanta() {
              var _j, _len1, _results....
 ````

If i understand it correctly the exit event is emitted when i call Phantom.exit(). However,  the phantom variable is never defined here. I don't know when/how it is suppose to be set but its always null for me and if evaluates to false, which means that it never gets removed from the phanta array. 

Now because phantom, or the instances in phanta is shared between the code using this module the gc will never clear these instances until the process exits fully. I managed to create a temporary sollution where i basically add the phantom instance to the ps object : 

````
sock = shoe(function shoe(stream) {
        var d;
        d = dnode({}, options.dnodeOpts);
        d.on('remote', function remote(phantom) {
          wrap(phantom);
          phantom.process = ps;
          ps.currentPhantom = phantom; //here
          phanta.push(phantom);
          return typeof cb === "function" ? cb(phantom) : void 0;
        });
````

And then removing it in ps.exit, i know this is a terrible sollution but until i can understand what i am doing wrong or this gets fixed. I Suppose its a working work around.

**Comment by adieuadieu** [comment]
I've run into this same issue. Out of curiosity, @Oted are you using Phantom 2.0? I don't seem to be experiencing the issue on 1.9.8 on my OS X machine, but do in production on Linux with phantom 2.0...
