### ISSUE TITLE
Reaching exit() before the script ends

### ISSUE THREAD

**Issue by matiasdecarli** [sgentle/phantomjs-node#254]
Im trying to run a webpage in which I have a script. This script send some messages to the console output. The issue is that Im reaching the exit() of the document before the script end its execution, so the console output gets truncated. If I use a timeout, the output logs fine. For example:

```
var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
	page.set('onConsoleMessage', function (arguments) {
  		console.log(arguments);
  	})

    page.open("test.html", function (status) {
		ph.exit();
    });
  });
});
```
logs 
```
TAP version 13
# timing test
ok 1 should be equal
```

But if I use a timeout instead
```
var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
	page.set('onConsoleMessage', function (arguments) {
  		console.log(arguments);
  	})

    page.open("test.html", function (status) {		
    });

    setTimeout(function(){
    	ph.exit();
    },1000)
  });
});
```
it logs the whole thing
```
TAP version 13
# timing test
ok 1 should be equal
not ok 2 should be equal
  ---
    operator: equal
    expected: 100
    actual:   104
  ...

1..2
# tests 2
# pass  1
# fail  1
```

Is there any way to wait until the script is completed? Thanks in advance

**Comment by adieuadieu** [comment]
This has to do with the asynchronous nature of what's going on. In other words, in your first example, ph.exit(); is called before whatever needs to happen in test.html has finished. 

The best way to signal to phantomjs that you've finished doing whatever it is that you're doing in the DOM, is to set some global variable in the DOM-scope which you then periodically check on from in phantom/node.
