### ISSUE TITLE
AssertionError: abnormal phantomjs exit code: -1073740791

### ISSUE THREAD

**Issue by Flaise** [sgentle/phantomjs-node#255]
Windows 7 64 bit

    >node --version
    v0.10.35
    >npm --version
    1.4.28
    >phantomjs --version
    2.0.0
    >node test.js
    
    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: abnormal phantomjs exit code: -1073740791
        at Console.assert (console.js:102:23)
        at ChildProcess.<anonymous> (...\node_modules\phantom\phantom.js:153:28)
        at ChildProcess.emit (events.js:98:17)
        at Process.ChildProcess._handle.onexit (child_process.js:820:12)

The contents of test.js is copied directly out of your readme file:

    var phantom = require('phantom');
    
    phantom.create(function (ph) {
      ph.createPage(function (page) {
        page.open("http://www.google.com", function (status) {
          console.log("opened google? ", status);
          page.evaluate(function () { return document.title; }, function (result) {
            console.log('Page title is ' + result);
            ph.exit();
          });
        });
      });
    });

**Comment by amir20** [comment]
Is there more details?

**Comment by Flaise** [comment]
I'm sorry but I ran into this issue nearly 7 months ago and I don't even remember what project I was working on at the time. I'm sure I wrote everything in that bug report that I thought at the time was important. :P
