### ISSUE TITLE
Undefined is not a function when calling page.set

### ISSUE THREAD

**Issue by fdvj** [sgentle/phantomjs-node#261]
Im getting this error:
```phantom stdout: TypeError: 'undefined' is not a function (evaluating 'key.split('.')')
< phantom stdout:   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:5436
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:5477
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:4526
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:4502
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:4382
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:4370
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:439 in ondata
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:595
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:408
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:1124
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:2033
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:2091
<   /home/fernando/Projects/SpinPlug/core-api/node_modules/phantom/shim.js:2223
```

Code (ignore the initializePhantom which is just to make sure phantom process doesnt stay alive when killing the app): ```function generateFromPath(filename, url, pageSize) {
    if (typeof filename !== 'string') {
      return 
    }

    if (!pageSize) {
      format: 'A4'
    }

    var deferred = Q.defer();
    initializePhantom(function(){
      ph.createPage(function(page){
        try {
          var file = path.normalize(tempdir + '/' + filename + '.pdf');
          page.open('http://localhost:' + sails.config.port + url, function(status){
            // Page set triggers the isue. Render below works correctly
            page.set({
              format: pageSize
            }, function() {
              page.render(file, function(){
                page.close();
                setForDeletion(file);
                return deferred.resolve(file);
              });
            });
          });
        } catch (e) {
          if (page) {
            page.close();
            return deferred.reject(e);
          }
        }
      });
    });
    return deferred.promise;
  }```

**Comment by fdvj** [comment]
Version 0.7.2, phantomjs version 1.9.8

**Comment by jonyet** [comment]
it seems odd to attempt page.set from within the instantiation of .open, no? maybe try breaking it out - that is where i always designate my settings:
```javascript
initializePhantom(function() {
    ph.createPage(function(page) {
        try {
            page.set({
                format: pageSize
            });
            var file = path.normalize(tempdir + '/' + filename + '.pdf');
            page.open('http://localhost:' + sails.config.port + url, function(status) {
                 function() {
                    page.render(file, function() {
                        page.close();
                        setForDeletion(file);
                        return deferred.resolve(file);
                    });
                });
            });
        } catch (e) {
            if (page) {
                page.close();
                return deferred.reject(e);
            }
        }
    });
});
```

**Comment by fdvj** [comment]
@jonyet Nope. Same issue outside the open. It only happens to me on the page.set. If I don't call it, I can render successfully but cannot set the page properties.

**Comment by jonyet** [comment]
well, not sure this will help you, but here is an example of page.set working just fine within my framework:

```javascript
Document.prototype.captureScreenshot = function(next) {
    console.log(">> Rendering screencap for " + this.id)
    var self = this;
    phantom.create(function(ph) {
        ph.createPage(function(page) {
            page.setContent(self.html);
            page.set("viewportSize", {
                width: 1920,
                height: 1080
            });
            page.set('onLoadFinished', function(success) {
            	var outputFile = './screenshots/screenshot-' + self.id + '.png';
            	page.render(outputFile);
            	ph.exit();
            	console.log(">> Render complete for " + self.id)
            	if (next)
            	    next(outputFile);
            })
        });
    });
}
```
hope this will help you out! using phantom 1.9.8 and module v 0.7.1

**Comment by fdvj** [comment]
Hey @jonyet thx for the help. My problem was in the ```page.set```. I was sending just an object as an argument, when I should have sent a key and a value. Since I was sending a callback, phantom was picking up the callback as the value and it therefore break.

Thanks for your sample code
