### ISSUE TITLE
Losing Page in my Cucumber.js Tests over Node

### ISSUE THREAD

**Issue by dschinkel** [sgentle/phantomjs-node#262]
Here's my code.  I lose the page as it ends up undefined in my first Cucumber.js step_definition and I"m not sure how to resolve this.  I don't know if I am just doing this all wrong with Phantomjs-node or what.  I've tried all sorts of things such as move the phantom.create to within the node exports function and also tried moving the end bracket (end of function) for the create to have it wrap all my Given functions for cucumber with no luck. 

//var assert = require('chai').assert;

var phantom = require('phantom'), _ph, _page;

phantom.create("--web-security=no", "--ignore-ssl-errors=yes", { port: 12345 }, function (ph) {

    _ph = ph;

    _ph.createPage(function(page) {
        _page = page;
        console.log("_page1:  " + _page); // here I DO get a valid page instance so all is good so far
        //_ph.exit();
    });
});

module.exports = function() {
    "use strict";

    this.Given(/^I visit the customers display page$/, function (callback) {

        console.log("_page:  " + _page); // problem is now _page instance above is lost, and is undefined here
        _page.open("/", function(status){
            console.log("status:  " + status);

            status.should.equal("success");
            _ph.exit();
            callback();
        });
    });

    this.Then(/^I should not see any customers listed$/, function (callback) {
        // not implemented
        callback.pending();
    });

    this.Given(/^there are some customers to view$/, function (callback) {
        // not implemented
        callback.pending();
    });

    this.When(/^I go to the customers display page$/, function (callback) {
        // not implemented
        callback.pending();
    });

    this.Then(/^I should see a list of customers grouped by Topic$/, function (callback) {
        // not implemented
        callback.pending();
    });

};

**Comment by amir20** [comment]
From the [readme](https://github.com/cucumber/cucumber-js), you need to probably do ` this.World = require("../support/world.js").World;` and expose something like 

```
// features/support/world.js
var webdriver = require("selenium-webdriver");

var World = function World(callback) {
  this.driver = new webdriver.Builder()
    .withCapabilities(webdriver.Capabilities.chrome())
    .build();
  callback();
}

module.exports = World;
```

I don't know cucumber.js that well. So hopefully this helps.

**Comment by amir20** [comment]
Also, I don't see the reason for using cucumber. http://blog.8thlight.com/kevin-liddle/2013/09/18/a-case-against-cucumber.html.

**Comment by dschinkel** [comment]
Nice!  I'm a huge follower of 8th Light.  Let me check that out, I've seen that post before.

**Comment by dschinkel** [comment]
I had a recent conversation about that post, and blogged about it: http://code-zest.blogspot.com/2015/04/do-you-need-cucumber-or-even-bdd.html

**Comment by amir20** [comment]
I went to write a comment on the post, and it didn't work. So here is my take...

I have never worked in an environment that PM or non technical people in the team wrote acceptance criteria. We had very intention for that to happen. But it just didn't happen. It go to a point that the cucumber tests got complex and only the engineers maintained. If you work in an environment that you can get them to write these tests then I think it makes sense. But if you can't get non-technical people to commit to these test cases, then I completely disagree that it could be more valuable, faster, or better in way to write code that needs to get parsed. It is not easier to read. It is more code to look at. And with your assumption of it actually being maintained by a PM, I don't think there is any other valid reason. 

I had wrote all this comment on the blog but it didn't work.

**Comment by dschinkel** [comment]
I think PMs can do it, and they are where he's at.  They do it in the
stories, there is no coding.  The language Gherkin syntax works perfectly
inside a story!  You type stories together as a team with the business
anyway, this is just a nice template to do it in.  And so at his
organization nobody is bitching, they love it.

I think the argument comes when people think PMs are to code too.  There's
no coding with Gherkin.  And if you do it and make it a standard language
in your iteration meetings and story application (agile app) I don't see
why it couldn't be something that works great.  All you do is paste the
Given, etc. wordage in and type in the requirement.  Simple.

So not sure if you're talking about the same argument...

**Comment by dschinkel** [comment]
So another thing can't I just use the PhantomJS-Node page instance and do I really need web driver if all I'm doing is opening a page and not really interacting with it yet?  I mean maybe later I'll find I need web driver but I figured I can just use page.open() for now to get my BDD tests to past in the minimal amount of config and PhantomJS needed.
