### ISSUE TITLE
Error in OpenShift: “phantomjs-node: You don't have 'phantomjs' installed”

### ISSUE THREAD

**Issue by JeanLebrument** [sgentle/phantomjs-node#264]
I have a problem when I want to run a script that uses phantomjs-node in OpenShift. The same script works well when I run it locally. 

I wrote a post on stackoverflow about my problem: http://stackoverflow.com/questions/29359766/error-in-openshift-phantomjs-node-you-dont-have-phantomjs-installed

Any suggestions?

**Comment by thomaswb** [comment]
This can be solved by using the CasperJS cartridge-- or maybe just the PhantomJS options are enough. Here was the solution for me:

https://github.com/daniel-sc/casperjs-cartridge/issues/2

**Comment by samtran123** [comment]
@JeanLebrument: could you solve the problem? Can you share it here? I have my nodejs application integrated with [phantomjs](https://github.com/amir20/phantomjs-node) works well on my Mac and doesn't work on Openshift. The nodejs app runs like there's no phantomjs code in it. There is no error from "rhc tail -a" neither. I have tried your link on stackoverflow and it didn't work.
