### ISSUE TITLE
onResourceReceived  support

### ISSUE THREAD

**Issue by dmitry1993** [sgentle/phantomjs-node#267]
Have been trying to find a way to hook up on "onResourceReceived",looks like it is not implemented.

http://phantomjs.org/api/webpage/handler/on-resource-received.html

**Comment by IonicaBizau** [comment]
I did it using:

```js
page.set('onResourceReceived', function() {
   /* do something */
});
```

**Comment by sanrodari** [comment]
Thanks @IonicaBizau, it works for me

**Comment by IonicaBizau** [comment]
@sanrodari Great! Glad to hear. :smile:
