### ISSUE TITLE
Using page.set('onConsoleMessage') crashes phantom

### ISSUE THREAD

**Issue by stuartlangridge** [sgentle/phantomjs-node#278]
$ grep version ./node_modules/phantom/package.json
    "version": "0.7.2",
    $ ./node_modules/.bin/phantomjs --version
    1.9.8
    $ node -e "var p=require('phantom'); p.create(function(ph){ ph.createPage(function(page){ page.set('onConsoleMessage', function() { console.log(arguments); }); page.open('http://www.google.com', function() { page.evaluate(function() { console.log('test'); }, function() { ph.exit(); }); }); }); });"

gives the error:

phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/775f41dc-c795-7b94-6e896b43-2fc6a8dc.dmp

**Comment by amir20** [comment]
Looks to be more Phantomjs bug. Closing.
