### ISSUE TITLE
How do I set a min-height for pageSize? 

### ISSUE THREAD

**Issue by caleuanhopkins** [sgentle/phantomjs-node#285]
Is there anyway to set the height of `viewportSize` option? I want to set a minimal width, I also want the height to be the full page. It looks like `viewportSize` requires a height and a width. I can get this to sort of work by remove `viewportSize` but the width is the smallest width the page is setup to render correct as per the `viewport` meta tag in the HTML.

**Comment by amir20** [comment]
From what I recall, I set the height to min height that I desired but phantom treated it as min-height. It didn't cut off the page and made the page longer.

**Comment by caleuanhopkins** [comment]
So just 'page.set('viewportSize', {width: 1200, min-height: 800});' ? Or is it somewhere else you are setting the min-height?

**Comment by amir20** [comment]
That's what I had. Does it work?

**Comment by caleuanhopkins** [comment]
@amir20 will test to see if this works later on today. Thanks for the prompt reply! :smile:

**Comment by caleuanhopkins** [comment]
hey @amir20, just got round to looking at this now, I get a `SyntaxError: Unexpected token - ` in node.js. Any chance you can share the code you used to get min-height working for you?

**Comment by caleuanhopkins** [comment]
@amir20 never mind, I changed height to `1` after re-reading your comment. Thanks for the help, this should really be added to the docs as a `tip` for grabbing full page screenshots. :+1:

**Comment by kachkaev** [comment]
For those who are facing this need in 2016, the answer is:
```js
page.property('viewportSize', {width: 1, height: 1});
```
