### ISSUE TITLE
Best way to wait to "wait for page" to load?

### ISSUE THREAD

**Issue by mcranston18** [sgentle/phantomjs-node#296]
Using node phantom, what is the recommended way to wait for a certain amount of seconds to evaluate a page and check to see which DOM elements are present? I attempted to wrap `page.evaluate` in a `setTimeout` for X seconds but this did not seem to work.

**Comment by onelesd** [comment]
Best thing to do is to put something like this in your function to be evaluated, and keep retrying the function every 500ms or so until you get a truthy return value:

```
function makeInput() {
  var el ;
  if (document.readyState === 'complete') {
    el = document.querySelector('input#someInput') ;
    if (el) {
      el.value = 'foo' ;
    }
  }
  return !! el ;
}
