### ISSUE TITLE
How to insert custom HTML which comes from a non-file?

### ISSUE THREAD

**Issue by IonicaBizau** [sgentle/phantomjs-node#301]
I have a variable which contains the HTML snippet which should be rendered as pdf. Is it possible to pipe it or send it to this module, without using a file? 

Thanks! :cake:

**Comment by Pentiado** [comment]
If this snipped should be a content then:
```
page.set('content', yourHTML);
```
and if you would like to use it in header or footer then some more magic required:
```
page.set('paperSize', {
  header: {
   contents: ph.callback(new Function('pageNum', 'numPages', `return '${yourHTML}'`));
  }
})
```

**Comment by IonicaBizau** [comment]
Oh, sounds good. Will look into it. Thanks! :cake:

**Comment by Levino** [comment]
This broke in v2. What to do now?
