### ISSUE TITLE
Does the render function accept a stream?

### ISSUE THREAD

**Issue by IonicaBizau** [sgentle/phantomjs-node#302]
Would be nice to check if the `page.render` provided argument is a writtable stream and if so, write the data there, without creating any files.

Is this possible?

**Comment by amir20** [comment]
It does not.

**Comment by amir20** [comment]
Look at this https://stackoverflow.com/questions/12403817/phantomjs-pipe-input link though. With some magic it might be possible.

**Comment by IonicaBizau** [comment]
Thanks. :apple:
