### ISSUE TITLE
POST message on page.open

### ISSUE THREAD

**Issue by michalmikolajczyk** [sgentle/phantomjs-node#303]
this reopens https://github.com/sgentle/phantomjs-node/issues/258

how can I have:
```
page.open('example.com', function (status) { ... });
```
send a POST request instead of GET? Is there some other method?

it would probably be something like
```
page.openPOST('example.com', { someData: 'value1' }, function (status) { ... });
```

**Comment by siboulet** [comment]
I also need this. PhantomJS supports that through an optional parameter to the open() method.

```
    page.open('https://...', {
      method: 'post',
      data: {
        field: 'value',
      },
    }, callback);

**Comment by agoldis** [comment]
+1

**Comment by rhussmann** [comment]
I ran into a similar need. @agoldis 's recommendation worked for me. Just ensure that `postBody` is a URL-encoded string, rather than a JSON-encoded string (hit this hiccup in my testing).
