### ISSUE TITLE
Tests fail on io.js

### ISSUE THREAD

**Issue by lukesneeringer** [sgentle/phantomjs-node#308]
The phantomjs-node tests fail on io.js, but you get a 0 exit status so Travis thinks they succeed:
https://travis-ci.org/sgentle/phantomjs-node/jobs/74149172

(Incidentally, I am having an issue _using_ phantomjs-node under io.js, which is what led me to discover this, but I have not figured out enough about those issues to make a useful bug report.)

**Comment by amir20** [comment]
In light of Node V4 being merged with io.js. I don't plan to support io.js anymore.
