### ISSUE TITLE
Cannot be installed on node 4.X.X because "weak" module is outdated

### ISSUE THREAD

**Issue by RyanK1m** [sgentle/phantomjs-node#312]
It seems included weak module is outdated (0.4.1) and this one won't properly installed on node 4.X.X

**Comment by jewkesy** [comment]
ditto.  I'm getting this on OSX

Workaround is to modify  <foo>/node_modules/phantom/node_modules/dnode/package.json and up-issue the 2 occurrences of 'weak' to '~1.0.0'

In the same folder run npm install to update the dependancies

**Comment by amir20** [comment]
If you send an update to `package.json` I can merge

**Comment by danieljuhl** [comment]
We are waiting for dnode to be published, weak has been bumped and so has dnode itself, but npm publish is still waiting.

**Comment by donaldpipowitch** [comment]
I guess it is published now, but it doesn't seem to solve the problem on Linux, because weak fails to install and dnode tries to use it (even if it is an optional dependecy). (https://github.com/substack/dnode/issues/169?)

**Comment by danieljuhl** [comment]
Any changes of getting the latest commits to phantomjs-node published as a new version to npm?

**Comment by amir20** [comment]
Published  `phantom@0.8.0`

**Comment by amir20** [comment]
Closing this ticket since it looks to be a `dnode` issue
