### ISSUE TITLE
abnormal phantomjs exit code: 127

### ISSUE THREAD

**Issue by rodmoreno** [sgentle/phantomjs-node#314]
Hi,

I am developing a web application that allows me to generate PDFs dynamically from the server to the client can be downloaded to their PC. The application is written in Node.js and for generating the PDFs we have decided to use your library: html5-to-pdf (using phantom).

In my local machine the application works without any problems but when I deployed the application on a Centos 7 in an EC2 AWS I have encountered an error trying to generate a pdf in the console displaying the following message:

    AssertionError: abnormal phantomjs exit code: 127
      at Console.assert (console.js:106:23)
      at ChildProcess.<anonymous> (/home/centos/addo-2.0/node_modules/html5-to-pdf/node_modules/phantom/phantom.js:153:28)
      at ChildProcess.emit (events.js:110:17)
      at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

 Could you help us solve this problem? Thanks in advance. 

Node version: 0.12.7
NPM version: 2.11.3

**Comment by amir20** [comment]
There is no details here for me to help. I ran phantom on Ubuntu and it worked. Try see if you can do it manually using `phantomjs` cli.

**Comment by rodmoreno** [comment]
When I tried to run the binary phantom.js marked me the following error:

    bin / phantomjs: error while loading shared libraries: libfontconfig.so.1: can not open shared object file: No such file or directory


Then I found this page:
https://github.com/ariya/phantomjs/issues/10904

which in turn I led me to this other page:
http://phantomjs.org/build.html

And just to install some dependencies the error solution, specifically I installed the following:

    sudo yum -y install gcc gcc-c ++ make flex bison gperf ruby \
    openssl-devel freetype-devel fontconfig-devel-devel libicu sqlite-devel \
       libpng-devel libjpeg-devel


And everything goes smoothly, thank you for your time.
