### ISSUE TITLE
Can't pass arguments to page.evaluate

### ISSUE THREAD

**Issue by AboulEinein** [sgentle/phantomjs-node#322]
I'm trying to pass a parameter to page.evaluate but parameter is not being sent

`var message = "Hello";`
`page.evaluate(function(message){`
        `document.getElementsByClassName("compose-message")[0].value = message;`
`});`

message is not readable, any idea how to get it working or if I'm missing something?

**Comment by bnolan** [comment]
You're defining an anonymous function but not calling it. I'm not sure what the correct way to do this is.

**Comment by amir20** [comment]
`evaluate` doesn't take a parameter. You could just use `message`.

**Comment by AboulEinein** [comment]
@amir20 but `message` is not visible in `evaluate`. How can I use a variable declared outside of `evaluate` function?

**Comment by amir20** [comment]
`message` is visible. It's called closures in javascript. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures I won't go in too much detail here. Put a question on stackoverflow :) Goodluck.

**Comment by AboulEinein** [comment]
@amir20 I understand closures, thanks anyways :)

**Comment by ICEDLEE337** [comment]
@AboulEinein This should work for you, but be aware that properties of config that are not 'primitives' will be stripped and consequently undefined inside `page.evaluate`
```js
var config = {message: 'hello world'};
page.evaluate(
function (evalConfig) {
    console.log(evalConfig.message);
},
function () {},
config);
```
