### ISSUE TITLE
shim.js is not installed in version 0.8.2

### ISSUE THREAD

**Issue by dp28** [sgentle/phantomjs-node#326]
I'm using phantom to render html to a png file, but after the 0.8.2 release I'm getting the following error (rather than a png):

```
phantom stderr: Can't open '/usr/local/lib/node_modules/layer-terminal/node_modules/phantom/shim.js'
```

`shim.js` does not exist in that directory, but it does if I peg phantom at 0.8.0 in my package.json and re-install, at which point it works again.

**Comment by amir20** [comment]
@piranna's commit broke this. Can you look?

**Comment by amir20** [comment]
I may have a fix. Will look at it tonight if it works.

**Comment by amir20** [comment]
@dp28 try again with `0.8.3`

**Comment by dp28** [comment]
Thanks, that's fixed it.
