### ISSUE TITLE
i make phantomjs2.0 and set its path in profile.But the phantom-node cannot find it 

### ISSUE THREAD

**Issue by toxic-johann** [sgentle/phantomjs-node#331]
i make phantomjs2.0 and set its path in profile.I can call it through cmd.but the phantom-node cannot find it.

![image](https://cloud.githubusercontent.com/assets/2577157/10961670/2d224412-83cc-11e5-890b-507f632c2c75.png)

however,if i install it through apt-get.i can get phantomjs1.9.0 installed,and phantom-node run.
can you tell me how to solve this question

**Comment by toxic-johann** [comment]
i solve it by put the bin into /usr/bin。

**Comment by zxqfox** [comment]
Actually, you should use PATH env variable for that.
