### ISSUE TITLE
No port or path provided

### ISSUE THREAD

**Issue by kuhnza** [sgentle/phantomjs-node#36]
Got the following error running when the example in the README:

> /Users/dave/Code/pycharm/hubify/browserpool/node_modules/phantom/node_modules/dnode/index.js:118
        throw new Error('no port or path provided');
              ^
> Error: no port or path provided
>    at D.listen (/Users/dave/Code/pycharm/hubify/browserpool/node_modules/phantom/node_modules/dnode/index.js:118:15)
>    at Object.create (/Users/dave/Code/pycharm/hubify/browserpool/node_modules/phantom/phantom.js:76:21)
>    at Object.<anonymous> (/Users/dave/Code/pycharm/hubify/browserpool/test/phantom.js:2:9)
>    at Module._compile (module.js:446:26)
>    at Object..js (module.js:464:10)
>    at Module.load (module.js:353:31)
>    at Function._load (module.js:311:12)
>    at Array.0 (module.js:484:10)
>    at EventEmitter._tickCallback (node.js:190:38)

Have a feeling this could be related to the version of dnode I'm running (latest), though it isn't clear what version of dnode phantomjs-node expects.

**Comment by amir20** [comment]
This is really old and I can't tell if it is fixed. I am going to close. Please reopen if still issue.
