### ISSUE TITLE
Looping createPage makes it consider only the fastest

### ISSUE THREAD

**Issue by coredump** [sgentle/phantomjs-node#38]
I am creating a tool that iterates over multiple URLs and returns the load times of each one. When I use the loop to create various workers with `phantom.create` I get the callbacks for all URLs (4, in my test). When I move the loop to after the worker creation and use it to create many `createaPages`  I only get 1 callback, that I suppose is the fastest one and first to end.
You can check the code here: https://github.com/coredump/pingmeister/blob/master/src/start.coffee#L11

**Comment by amir20** [comment]
Cleaning out old bugs.
