### ISSUE TITLE
page.set('content') does't work

### ISSUE THREAD

**Issue by skotchio** [sgentle/phantomjs-node#68]
I'm trying to get screenshot of some content by like the following example:

    phantom.create(function(ph) {
        ph.createPage(function(page) {
          page.set('content', '<html><body>blah blah blah</body></html>');
          page.render('page.png');
        })
     });

But after the code above executed I get empty page.png file without the content.

**Comment by pscollins** [comment]
`page.set` is async, so you need to use 

    phantom.create (ph) ->
        ph.createPage (page) ->
          page.setContent '<html><body>blah blah blah</body></html>', ->
            page.render('page.png')

**Comment by amir20** [comment]
Looks like this was answered.

**Comment by jonyet** [comment]
sorry, maybe i'm missing something but using what @adishua is not working for me.

```javascript
Document.prototype.captureScreenshot = function(next){
	console.log(">> Rendering screencap for " + this.id)
	var self = this;
	phantom.create(function (ph) {
	  ph.createPage(function (page) {
	  	page.setContent(self.html, function(){
	  		var outputFile = './screenshots/screenshot-' + self.id + '.png';
	  		page.render(outputFile);
	  		ph.exit();
	  		console.log(">> Render complete for " + self.id)
	  			if(next)
	  				next(outputFile);
	  	});
	  });
	});
}
```
even if i sub out self.html with 
```javascript
'<html><body>blah blah blah</body></html>'
```
the method simply hangs once attempting page.setContent. something obvious i'm missing perhaps?

**Comment by Verikon** [comment]
I'm getting an empty render too jonyet; did you resolve this?

**Comment by jonyet** [comment]
@Verikon yep! i had to declare my settings after createPage() and then do the render upon the onLoadFinished event. the sample below is not particularly fast, so i plan on later breaking phantom out as a service and optimizing it. here is my finished solution:
```javascript
Document.prototype.captureScreenshot = function(next) {
    console.log(">> Rendering screencap for " + this.id)
    var self = this;
    phantom.create(function(ph) {
        ph.createPage(function(page) {
            page.setContent(self.html);
            page.set("viewportSize", {
                width: 1920,
                height: 1080
            });
            page.set('onLoadFinished', function(success) {
            	var outputFile = './screenshots/screenshot-' + self.id + '.png';
            	page.render(outputFile);
            	ph.exit();
            	console.log(">> Render complete for " + self.id)
            	if (next)
            	    next(outputFile);
            })
        });
    });
}
```

**Comment by Verikon** [comment]
Very nice! :) TYVM.

**Comment by roc** [comment]
Really helpful, thanks @jonyet!
