### ISSUE TITLE
page.set 'clipRect' doesn't work

### ISSUE THREAD

**Issue by wuhaixing** [sgentle/phantomjs-node#95]
Here is my code:
     page.evaluate (-> document.getElementById('content').getBoundingClientRect()),(result) ->
                page.set 'clipRect',result
                console.log result
                page.render ("content.pdf"), =>

and I can get the correct result,but not the correct clipRect in output file.Why?

**Comment by jakobloekke** [comment]
I also cannot get this to work.

**Comment by meconlin** [comment]
+1

**Comment by meconlin** [comment]
Actually, I read the README...

Properties can't be get/set directly, instead use ```page.get('version', callback)``` or ```page.set('viewportSize', {width:640,height:480})```, etc. Nested objects can be accessed by including dots in keys, such as ```page.set('settings.loadImages', false)```

And then tried this:
```
page.set('clipRect', {
             top:    result.top,
             left:   result.left,
             width:  result.width,
             height: result.height
          });
```

Works like a champ.
