### ISSUE TITLE
Error detected in the version 0.5.2 when using phantom arguments[not present in the version 0.5.1]

### ISSUE THREAD

**Issue by BenRhouma** [sgentle/phantomjs-node#96]
I'm calling phantom via this piece of code
var ph;
phantom.create(vars.PHANTOM_CLI_ARGUMENTS, function (phe) {
    ph = phe
}, null, null);
//
vars.PHANTOM_CLI_ARGUMENTS value ='--load-images=no';

I get this error 
/app/node_modules/phantom/phantom.js:82 
Aug 12 13:02:47 clickcounter app/web.1:        if ((_ref = options.binary) == null) { 
Aug 12 13:02:47 clickcounter app/web.1:                           ^ 
Aug 12 13:02:47 clickcounter app/web.1:  TypeError: Cannot read property 'binary' of null 
Aug 12 13:02:47 clickcounter app/web.1:      at Object.module.exports.create (/app/node_modules/phantom/phantom.js:82:26) 
Aug 12 13:02:47 clickcounter app/web.1:      at Object.<anonymous> (/app/htmlSnapShot.js:20:9) 
Aug 12 13:02:47 clickcounter app/web.1:      at Module._compile (module.js:456:26) 
Aug 12 13:02:47 clickcounter app/web.1:      at Object.Module._extensions..js (module.js:474:10) 
Aug 12 13:02:47 clickcounter app/web.1:      at Module.load (module.js:356:32) 
Aug 12 13:02:47 clickcounter app/web.1:      at Function.Module._load (module.js:312:12) 
Aug 12 13:02:47 clickcounter app/web.1:      at Module.require (module.js:364:17) 
Aug 12 13:02:47 clickcounter app/web.1:      at require (module.js:380:17) 
Aug 12 13:02:47 clickcounter app/web.1:      at Object.<anonymous> (/app/app.js:7:14) 
Aug 12 13:02:47 clickcounter app/web.1:      at Module._compile (module.js:456:26) 
Aug 12 13:02:48 clickcounter heroku/web.1:  Process exited with status 8

**Comment by amir20** [comment]
Cleaning out old bugs.
